services:
  postgres:
    image: 'bitnami/postgresql:latest'
    ports:
      - '57184:5432'
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_PASSWORD: auth_pw
      POSTGRES_USER: auth_user
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: